#!/usr/bin/env node
/**
 * Pulls the ABIs Foundry just compiled into a typed module the app imports.
 * Run after `npm run contracts:build`.
 */
import { readFile, writeFile, access } from 'node:fs/promises'
import path from 'node:path'

const root = process.cwd()
const artifacts = [
  ['bachaGameAbi', 'contracts/out/BachaGame.sol/BachaGame.json'],
  ['bachaVaultAbi', 'contracts/out/BachaVault.sol/BachaVault.json'],
]

const chunks = [
  '// Generated by scripts/export-abi.mjs — do not edit by hand.',
  '// Regenerate with: npm run contracts:build && node scripts/export-abi.mjs',
  '',
]

for (const [name, rel] of artifacts) {
  const file = path.join(root, rel)
  try {
    await access(file)
  } catch {
    console.error(`missing artifact ${rel} — run \`npm run contracts:build\` first`)
    process.exit(1)
  }
  const { abi } = JSON.parse(await readFile(file, 'utf8'))
  chunks.push(`export const ${name} = ${JSON.stringify(abi, null, 2)} as const`, '')
}

const out = path.join(root, 'src/lib/contracts/abis.ts')
await writeFile(out, chunks.join('\n'))
console.log(`wrote ${path.relative(root, out)}`)
